name: Build and Test with Maven
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
   build-and-test:
     name: Java CI - test
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
       - name: Set up Java
         uses: actions/setup-java@v1
         with:
           java-version: 1.8
       - name: Inject dummy example config
         working-directory: duo-example
         run: printf "duo.clientId=DIAAAAAAAAAAAAAAAAAA\nduo.clientSecret=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\nduo.api.host=example.duosecurity.com\nduo.redirect.uri=http://localhost:8080\nduo.failmode=CLOSED\n" > ./src/main/resources/application.properties
       - name: Build and test with Maven
         run: mvn -B install
       - name: Lint with checkstyle
         run: mvn checkstyle:check
       - name: Verify example starts
         working-directory: duo-example
         run: mvn spring-boot:start
       - name: Verify release profile works
         run: mvn -P release package
